# Generated by Django 5.0.1 on 2024-02-04 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabdrivers', '0002_rename_taxi_cab'),
    ]

    operations = [
        migrations.CreateModel(
            name='driver_signup_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email_Address', models.EmailField(max_length=100)),
                ('Mobile_Number', models.CharField(max_length=10)),
                ('City', models.CharField(choices=[('Ten', 'Tenkasi'), ('Kdnl', 'Kadayanallur'), ('Tvl', 'Tirunelveli')], max_length=10)),
                ('Vehicle', models.CharField(choices=[('cr', 'Car'), ('bk', 'Bike'), ('Au', 'Auto')], max_length=6)),
                ('Vehicle_Number', models.CharField(max_length=10)),
                ('Bank_Account', models.BigIntegerField()),
                ('Profile_Picture', models.ImageField(upload_to='media/cabdrivers/profile')),
                ('License_Number', models.CharField(max_length=20)),
                ('Aadhaar_Card', models.CharField(max_length=12)),
                ('RC_Photo', models.ImageField(upload_to='media/cabdrivers/RC')),
                ('Vehicle_Insurance', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Cab',
        ),
        migrations.DeleteModel(
            name='Driver',
        ),
    ]
